package wsn;

import java.awt.*;
import java.io.*;
import javax.swing.*;
import java.util.*;
public class WSNApplicationDemo4C extends javax.swing.JFrame {
 WSN wsn;
 WSNApplicationDemo4 a4;
 public DefaultListModel listModel1=new DefaultListModel();
  public WSNApplicationDemo4C(WSNApplicationDemo4 a4,WSN wsn) {
    initComponents();
    this.a4=a4;
    this.wsn=wsn;
                int width=Toolkit.getDefaultToolkit().getScreenSize().width;
        int h=Toolkit.getDefaultToolkit().getScreenSize().height-20;

        int w2=(width * 80000)/100000;
        int h2=(h * 80000)/100000;

        setSize(w2,h2);

        setLocation((width-w2)/2,(h-h2)/2);

        Image iconImage=new ImageIcon(getClass().getClassLoader().getResource("crtc_logo_t.gif")).getImage();
        setIconImage(iconImage);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")

  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jComboBox1 = new javax.swing.JComboBox();
    jComboBox2 = new javax.swing.JComboBox();
    jComboBox3 = new javax.swing.JComboBox();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jPanel5 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();

    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("wsn/Bundle"); 
    setTitle(bundle.getString("WSNApplicationDemo4C.title")); 
    setName("Form"); 

    jPanel1.setName("jPanel1"); 
    jPanel1.setLayout(new java.awt.GridLayout(3, 1));

    jPanel3.setName("jPanel3"); 
    jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    jButton1.setFont(jButton1.getFont());

    jButton1.setText(bundle.getString("WSNApplicationDemo4C.jButton1.text")); 
    jButton1.setName("jButton1"); 
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel3.add(jButton1);

    jComboBox1.setFont(jComboBox1.getFont());
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox1.setName("jComboBox1"); 
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox1ActionPerformed(evt);
      }
    });
    jPanel3.add(jComboBox1);

    jComboBox2.setFont(jComboBox2.getFont());
    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox2.setName("jComboBox2"); 
    jComboBox2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox2ActionPerformed(evt);
      }
    });
    jPanel3.add(jComboBox2);

    jComboBox3.setFont(jComboBox3.getFont());
    jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox3.setName("jComboBox3"); 
    jComboBox3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox3ActionPerformed(evt);
      }
    });
    jPanel3.add(jComboBox3);

    jButton2.setFont(jButton2.getFont());
    jButton2.setText(bundle.getString("WSNApplicationDemo4C.jButton2.text")); 
    jButton2.setName("jButton2"); 
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });
    jPanel3.add(jButton2);

    jButton3.setFont(jButton3.getFont());
    jButton3.setText(bundle.getString("WSNApplicationDemo4C.jButton3.text")); 
    jButton3.setName("jButton3"); 
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });
    jPanel3.add(jButton3);

    jButton4.setFont(jButton4.getFont());
    jButton4.setText(bundle.getString("WSNApplicationDemo4C.jButton4.text")); 
    jButton4.setName("jButton4"); 
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });
    jPanel3.add(jButton4);

    jPanel1.add(jPanel3);

    jPanel5.setName("jPanel5"); 
    jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    jLabel3.setName("jLabel3"); 
    jPanel5.add(jLabel3);

    jLabel2.setFont(jLabel2.getFont());
    jLabel2.setText(bundle.getString("WSNApplicationDemo4C.jLabel2.text")); 
    jLabel2.setName("jLabel2"); 
    jPanel5.add(jLabel2);

    jPanel1.add(jPanel5);

    jPanel4.setName("jPanel4"); 
    jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

    jLabel1.setFont(jLabel1.getFont());
    jLabel1.setText(bundle.getString("WSNApplicationDemo4C.jLabel1.text")); 
    jLabel1.setName("jLabel1"); 
    jPanel4.add(jLabel1);

    jPanel1.add(jPanel4);

    getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

    jPanel2.setName("jPanel2"); 
    jPanel2.setLayout(new java.awt.BorderLayout());

    jScrollPane1.setName("jScrollPane1"); 

    jList1.setModel(listModel1);
    jList1.setName("jList1"); 
    jList1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jList1MouseClicked(evt);
      }
    });
    jList1.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        jList1KeyReleased(evt);
      }
    });
    jScrollPane1.setViewportView(jList1);

    jPanel2.add(jScrollPane1, java.awt.BorderLayout.WEST);

    jScrollPane2.setName("jScrollPane2"); 

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jTextArea1.setName("jTextArea1"); 
    jScrollPane2.setViewportView(jTextArea1);

    jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

    pack();
  }

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
  a4.a4b.setSelectedId(getSelectedId());
  if(!a4.a4b.isVisible()) a4.a4b.setVisible(true);
  a4.a4b.toFront();
}

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
      String dir0="apps"+File.separator+"cr-wsn"+File.separator+"data",sel="";
      String dir=(String)jComboBox1.getSelectedItem();
        File datalog=new File(dir0+File.separator+dir);

    File[] contents1=datalog.listFiles();
    jComboBox2.removeAllItems();
    jComboBox3.removeAllItems();
    if(contents1!=null && contents1.length>0){
        Arrays.sort(contents1);
       for(int i=0;i<contents1.length;i++){
           if(contents1[i].isDirectory()){
              jComboBox2.addItem(contents1[i].getName());
              sel=contents1[i].getName();
           }
       }
       if(sel.length()>0) jComboBox2.setSelectedItem(sel);
    }

}

private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {
      String dir0="apps"+File.separator+"cr-wsn"+File.separator+"data",sel="";
      String dir1=(String)jComboBox1.getSelectedItem();
      String dir2=(String)jComboBox2.getSelectedItem();
        File datalog=new File(dir0+File.separator+dir1+File.separator+dir2);

    File[] contents1=datalog.listFiles();
    jComboBox3.removeAllItems();
    if(contents1!=null && contents1.length>0){
        Arrays.sort(contents1);
       for(int i=0;i<contents1.length;i++){
           if(contents1[i].isDirectory()){
              jComboBox3.addItem(contents1[i].getName());
              sel=contents1[i].getName();
           }
       }
       if(sel.length()>0) jComboBox3.setSelectedItem(sel);
    }
}

private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {
    String dir0="apps"+File.separator+"cr-wsn"+File.separator+"data";
    String dir1=(String)jComboBox1.getSelectedItem();
    String dir2=(String)jComboBox2.getSelectedItem();
    String dir3=(String)jComboBox3.getSelectedItem();
    File datalog=new File(dir0+File.separator+dir1+File.separator+dir2+File.separator+dir3);

    File[] contents1=datalog.listFiles();

    listModel1.removeAllElements();
    if(contents1!=null && contents1.length>0){
       for(int i=0;i<contents1.length;i++){
           if(contents1[i].isFile()){
              String fn=contents1[i].getName();
                listModel1.addElement(fn);
           }
       }
    }
}

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
 renewFileList();
}

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
    String dir0="apps"+File.separator+"cr-wsn"+File.separator+"data";
    String dir1=(String)jComboBox1.getSelectedItem();
    String dir2=(String)jComboBox2.getSelectedItem();
    String dir3=(String)jComboBox3.getSelectedItem();
  if(jList1.getSelectedValues()!=null){
    Object o[]=jList1.getSelectedValues();
    for(int i=0;i<o.length;i++){
      String filename=dir0+File.separator+dir1+File.separator+dir2+File.separator+dir3+File.separator+(String)o[i];
      new File(filename).delete();
      listModel1.removeElement(o[i]);
    }
  }
  jTextArea1.setText("");
}

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    String dir0="apps"+File.separator+"cr-wsn"+File.separator+"data";
    String dir1=(String)jComboBox1.getSelectedItem();
    String dir2=(String)jComboBox2.getSelectedItem();
    String dir3=(String)jComboBox3.getSelectedItem();
    File datalog=new File(dir0+File.separator+dir1+File.separator+dir2+File.separator+dir3);

    File[] contents1=datalog.listFiles();

    listModel1.removeAllElements();
    if(contents1!=null && contents1.length>0){
       for(int i=0;i<contents1.length;i++){
           if(contents1[i].isFile()){
             contents1[i].delete();
           }
       }
    }
    jTextArea1.setText("");
}

private void jList1KeyReleased(java.awt.event.KeyEvent evt) {
if(evt.getKeyCode()==38 || evt.getKeyCode()==40 )  showFile();
}

private void jList1MouseClicked(java.awt.event.MouseEvent evt) {
  showFile();
}
public void showFile(){
    String dir0="apps"+File.separator+"cr-wsn"+File.separator+"data";
    String dir1=(String)jComboBox1.getSelectedItem();
    String dir2=(String)jComboBox2.getSelectedItem();
    String dir3=(String)jComboBox3.getSelectedItem();
  String filename="";
  StringBuffer sb=new StringBuffer();
  if(jList1.getSelectedValue()!=null){
    filename=dir0+File.separator+dir1+File.separator+dir2+File.separator+dir3+File.separator+(String)jList1.getSelectedValue();
      File f=new File(filename);
      try{
      if(f.exists() && f.isFile()){
        FileInputStream in=new FileInputStream(filename);
        BufferedReader d= new BufferedReader(new InputStreamReader(in));
        while(true){
	  String str1=d.readLine();
	  if(str1==null) {in.close(); d.close(); break; }
          sb.append(str1+"\r\n");
        }
	in.close();
	d.close();
        jTextArea1.setText(sb.toString());
          }
           }catch(FileNotFoundException e){
               e.printStackTrace();
           }
    catch(IOException e){
        System.out.println("IO Error in reading "+filename+" file.\r\n");
        e.printStackTrace();
    }
       String dataSrc=(String)jList1.getSelectedValue();
       dataSrc=dataSrc.substring(0, dataSrc.length()-13);
       if(dataSrc.indexOf("_")>-1) dataSrc=wsn.w.replace(dataSrc, "_", ":");
       dataSrc=wsn.getDataSrcId(wsn.w.getGNS(1), dataSrc);
       Iterator it=a4.itemData.values().iterator();
       String da[];
       boolean found=false;
       for(;it.hasNext();){
          da=wsn.w.csvLineToArray((String)it.next()); 
          if((da[1]+":"+da[2]).equals(wsn.w.getGNS(6)+":"+dataSrc)){
            found=true;
            boolean online=wsn.w.checkOneVar(da[4], 0);
            ImageIcon omg;
            if(online) omg= WSNApplicationDemo4.omgOn;
             else omg=WSNApplicationDemo4.omgOff;

     jLabel3.setIcon(omg);
            jLabel2.setText("No: "+da[0]+"        "+da[1]+":"+da[2]+",      status: "+(online? "online":"offline")+",       Location: "+da[3]);
            break;
          }
       }
      if(!found) {
        jLabel3.setIcon(null);
        jLabel2.setText("");
      }
   } 
 }

public void renewFileList(){
    listModel1.removeAllElements();
    String dir="apps"+File.separator+"cr-wsn"+File.separator+"data",sel="";
    File datalog=new File(dir);
    if(!datalog.exists()) datalog.mkdir();
    File[] contents1=datalog.listFiles();
    jComboBox1.removeAllItems();
    jComboBox2.removeAllItems();
    jComboBox3.removeAllItems();
    if(contents1!=null && contents1.length>0){
       Arrays.sort(contents1);
       for(int i=0;i<contents1.length;i++){
           if(contents1[i].isDirectory()){
              jComboBox1.addItem(contents1[i].getName());
              sel=contents1[i].getName();
           }
       }
       if(sel.length()>0) jComboBox1.setSelectedItem(sel);
    }
}
public void setSelectedId(String id){
  if(id!=null && a4.itemData.get(id)!=null){
    String data[]=wsn.w.csvLineToArray((String)a4.itemData.get(id));
    String item=(data[1].equals(wsn.w.getGNS(6))? "":data[1]+"_")+data[2]+"_"+wsn.formatter2.format(new Date()).subSequence(0,8)+".txt";
    jList1.setSelectedValue(item, true);
  } else jList1.setSelectedIndex(0);
}
public String getSelectedId(){
  String rtn=null;
  if(jList1.getSelectedValue()!=null){
    String item=(String)jList1.getSelectedValue();
    item=item.substring(0, item.lastIndexOf("_"));
    String ip=wsn.w.getGNS(6);
    if(item.indexOf("_")!=-1){
      ip=item.substring(0,item.indexOf("_"));
      item=item.substring(item.indexOf("_")+1);
    }
    Iterator it=a4.itemData.keySet().iterator();
    for(;it.hasNext();){
      String key=(String)it.next();
      String data[]=wsn.w.csvLineToArray((String)a4.itemData.get(key));
      if(data[2].equals(item)){
        rtn=key;
        break;
      }
    }
  }
  return rtn;
}

  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JComboBox jComboBox1;
  private javax.swing.JComboBox jComboBox2;
  private javax.swing.JComboBox jComboBox3;
  public javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JList jList1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTextArea jTextArea1;

}